-- Employee
create table Employee (
    employee_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint employee_pk primary key (employee_id),

    fio VARCHAR2(100),
    date_of_birth date,
    phone_number varchar2(13),
    email varchar2(100),
    live_address varchar2(100),
    resume_text varchar2(1000),
    status varchar2(20) default 'new'
);

-- Employer
create table Employer (
    employer_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint employer_pk primary key (employer_id),

    fio VARCHAR2(100),
    company_name varchar2(100),
    phone_number varchar2(13),
    email varchar2(100),
    company_address varchar2(100)
);

-- Manager
create table Manager (
    manager_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint manager_pk primary key (manager_id),

    fio VARCHAR2(100),
    phone_number varchar2(13),
    email varchar2(100)
);

-- Vacancy
create table Vacancy (
    vacancy_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint vacancy_pk primary key (vacancy_id),

    employer_id integer not null,
    vacancy_title VARCHAR2(100) not null,
    description VARCHAR2(500),
    requirements VARCHAR2(500),
    salary number(10,2),
    open_date date not null,
    close_date date,
    status varchar2(20) default 'open',

    constraint vacancy_employer_fk
        foreign key (employer_id)
        references Employer(employer_id)
        on delete cascade
);

-- Application
create table Application (
    application_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint application_pk primary key (application_id),

    vacancy_id integer not null,
    employee_id integer not null,
    application_date date not null,
    status varchar2(20) default 'new',

    constraint application_vacancy_fk
        foreign key (vacancy_id)
        references Vacancy(vacancy_id)
        on delete cascade,

    constraint application_employee_fk
        foreign key (employee_id)
        references Employee(employee_id)
        on delete cascade,

    constraint application_unique
        unique (vacancy_id, employee_id)
);

-- Interview
create table Interview (
    interview_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint interview_pk primary key (interview_id),

    application_id integer not null,
    interview_date date not null,
    interview_time timestamp,
    manager_id integer not null,
    result varchar2(20) default 'pending',

    constraint interview_application_fk
        foreign key (application_id)
        references Application(application_id)
        on delete cascade,

    constraint interview_manager_fk
        foreign key (manager_id)
        references Manager(manager_id)
);

-- Status_History
create table Status_History (
    history_id integer generated by default as identity
        (start with 1 increment by 1),
    constraint history_pk primary key (history_id),

    application_id integer not null,
    status varchar2(20) not null,
    changed_by integer not null,
    changed_by_role varchar2(20),
    change_date date default sysdate,

    constraint history_application_fk
        foreign key (application_id)
        references Application(application_id)
        on delete cascade
);